service: swdemo

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:580352614414:table/swdemoTable

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: 
          path: /hello
          method: get

  swdemo:
    handler: src/infrastructure/controllers/GetModifiedDataController.getModifiedDataController
    events:
      - httpApi: 
          path: /swdemo
          method: get

  addStarship:
    handler: src/infrastructure/controllers/SaveStarshipController.saveStarship
    events:
      - httpApi: 
          path: /starship
          method: post

  listStarship:
    handler: src/infrastructure/controllers/GetAllStarshipsController.getAllStarShips
    events:
      - httpApi: 
          path: /starship
          method: get

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  # - serverless-dynamodb-local
  - serverless-offline
 
resources:
  Resources:
    swdemo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: swdemoTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1