service: swdemo

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: 
          path: /hello
          method: get

  swdemo:
    handler: src/infrastructure/controllers/GetModifiedDataController.getModifiedDataController
    events:
      - httpApi: 
          path: /swdemo
          method: get

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  # - serverless-dynamodb-local
  - serverless-offline
